In [8]:
# !pip install mysql-connector-python (not industry standard, throw warning because Pandas prefers a SQLAlchemy engine, not a raw MySQL connector.)

In [ ]:
%pip install sqlalchemy pymysql

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.44-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.2.4-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading sqlalchemy-2.0.44-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 781.0 kB/s eta 0:00:03
   --------- ------------------------------ 0.5/2.1 MB 781.0 kB/s eta 0:00:03
   --------- ------------------------------ 0.5/2.1 MB 781.0 kB/s eta 0:00:03
   -------------- ------------------------- 0.8/2.1 MB 586.6 kB/s eta 0:00:03
   -------------- ------------------------- 0.8/2.1 MB 586.6 kB/s eta 0:00:03
   ------------------- -------------------- 1.0/2.1 MB 637.5 kB/s eta 0:00:02
   ------------------- -------------------- 1.0/2.1 MB 637.5 kB/s eta 0:00:02
   ------------------------ --------------- 1.3/2.1 MB 634.5 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.1 MB 666.7 kB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 666.7 kB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 666.7 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 622.7 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 622.7 kB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 646.9 kB/s  0:00:03
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Downloading greenlet-3.2.4-cp313-cp313-win_amd64.whl (299 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, pymysql, greenlet, sqlalchemy

   ---------- ----------------------------- 1/4 [pymysql]
   ---------- ----------------------------- 1/4 [pymysql]
   ---------- ----------------------------- 1/4 [pymysql]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ---------------------------------------- 4/4 [sqlalchemy]

Successfully installed greenlet-3.2.4 pymysql-1.1.2 sqlalchemy-2.0.44 typing-extensions-4.15.0

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd

In [ ]:
import json
from sqlalchemy import create_engine

# Load secrets
with open('secrets.json', 'r') as f:
    secrets = json.load(f)

# Create connection
engine = create_engine(
    f"mysql+pymysql://{secrets['DB_USER']}:{secrets['DB_PASSWORD']}@{secrets['DB_HOST']}/{secrets['DB_NAME']}"
)

# Test connection
try:
    connection = engine.connect()
    print("Connected to database!")
    connection.close()
except Exception as e:
    print(f"Connection failed: {e}")

In [19]:
sales_query = "SELECT * FROM sales"
inventory_query = "SELECT * FROM inventory"

sales_df = pd.read_sql(sales_query, engine)
inventory_df = pd.read_sql(inventory_query, engine)

In [20]:
sales_df.head()

,sale_id,date_of_sale,item_name,category,quantity_sold,unit_price,payment_mode,customer_type
0,1,08-09-2025,Coffee,Beverage,7,36.0,Card,Staff
1,2,25-10-2025,Sandwich,Snacks,7,Rs 12,UPI,Student
2,3,15-10-2025,Tea,Beverage,6,26â‚¹,UPI,Staff
3,4,02-10-2025,Chips,Snacks,3,36â‚¹,Card,Student
4,5,18-10-2025,Juice,Beverage,2,30.0,Cash,Student

In [21]:
inventory_df.head()

,inventory_id,date_of_entry,item_name,stock_in,stock_used,remaining_stock,unit_cost,supplier_name
0,1,30-10-2025,Tea,53,40,13,5â‚¹,FreshFoods Pvt Ltd
1,2,28-10-2025,Pasta,57,38,19,Rs 33,DailySupply Co.
2,3,16-08-2025,Chips,59,43,16,Rs 23,BeverageHub
3,4,06-10-2025,Juice,76,59,17,12,FreshFoods Pvt Ltd
4,5,23-10-2025,Juice,38,12,26,Rs 40,SuperSnacks Traders

In [22]:
sales_df.to_csv("../data/raw/sales.csv",index=False)
inventory_df.to_csv("../data/raw/inventory.csv",index=False)